name: every-15m-cron-job
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API route fetching new documents
        run: |
          curl --request GET \
          --url '${{ secrets.UPDATE_DOCS_ENDPOINT }}' \
          --header 'Authorization: Bearer ${{ secrets.CRON_JOB_SECRET }}'

name: daily-midnight-cleanup
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API route fetching new documents
        run: |
          curl --request GET \
          --url '${{ secrets.CLEANUP_FILES_ENDPOINT }}' \
          --header 'Authorization: Bearer ${{ secrets.CRON_JOB_SECRET }}'